### ISSUE TITLE
License & Commercial Permissions

### ISSUE THREAD

**Issue by sheafferusa** [bipio-server/bipio#21]
"If you'd like to integrate BipIO with your proprietary system, GPLv3 is likely incompatible. To secure a Commercial OEM License for Bipio, please reach us"
Well, could someone please explain this statement? As far as I know, GPL licenses mostly allow use in proprietary for profit systems, and not the contrary.

**Comment by sheafferusa** [comment]
@cmawhorter
Yes, that's absolutely correct. No distribution means no compulsion to release the source code, under any of the GPL licenses including the older 2.0 and the latest 3.0. 
However, this case (The Software here) is specifically in stark  violation with the fundamental & core principles on the basis of which, The GPL licenses were created. However, the code, once released under the GPL license, remains GPL for life, as long as anyone/a user has the original source code which was released under the GPL. What that means is, irrespective of whatever changes have been put forward, the original code grants the users all the rights under the GPL license. In this case, even if a user refuses to release the source code when not distributing the software in binary or code, he/she cannot be challanged legally, as he doesn't need to release the code, under the terms of GPL license for the code that he is using. What that means is, irrespective of whatever restriction the author/company impose on the code previously licensed under GPL, there is legally no compulsion   for any of the former users to abide by them, as long as he is in compliance with the GPL license. 

PS: well, a reply on these lines has been given because there has been absolutely no response from the developers/owners or the company associated with the aoftware/source code. On top of that, the thread has been closed, depicting the arrogance of the company and it's decision to leave the thread dead. 

Thanks once again! 
-Animesh

**Comment by mjpearson** [comment]
The choice of GPL for this project is to promote the open sourcing of user modules or stacks created with the bipio framework while also being mindful of the realities faced by commercial customers.  A similar sentiment as to how to approach the proprietary problem was flatly put forward by Stallman (http://www.fsf.org/blogs/rms/selling-exceptions) and so have taken the view that this is a pragmatic approach.

In a nutshell, the only restrictions of the software are those imposed by GPLv3, the legal semantics of which are better suited to legal channels. If a commercial enterprise is unable to honor the license, as copyright holder we can tailor a solution to suit and provide support for integrating proprietary code in a technology partner role which includes managed services, support and infrastructure. This doesn't run counter to the nature of GPLv3 and merely reinforces to commercial entities to take an open source approach where possible.

http://www.gnu.org/licenses/gpl-faq.html#GPLInProprietarySystem
