### ISSUE TITLE
How can I build Bips (workflow) without web_interface

### ISSUE THREAD

**Issue by EricCat** [bipio-server/bipio#41]
I want to build bips without mount web_interface. I found nothing from wiki. How can I do this?
Thanks very much

**Comment by mjpearson** [comment]
Hey Eric, bipio is API-first, so everything you can see in the UI can also be done via it's API.  

Documentation can be found at :

API Overview - https://github.com/bipio-server/bipio/wiki#api

Creating Bips - https://github.com/bipio-server/bipio/wiki/Bips

Sample Request/response - https://github.com/bipio-server/bipio/wiki/Bips#requestresponse-example

Building Transformation templates - https://github.com/bipio-server/bipio/wiki/Transforms-And-Templates

You could also model an integration graphically in the hosted UI under bips > {your bip} > Data View, grab that JSON and post it using your favorite REST client (adjusting the channel id's accordingly)

**Comment by EricCat** [comment]
@mjackson Thanks very much. It help me a lots
