### ISSUE TITLE
domain cannot changed when set domain_public

### ISSUE THREAD

**Issue by EricCat** [bipio-server/bipio#43]
I set ``domain_public`` in config with ``localhost:5000`` and ``domain`` is ``localhost``. but  when I setup bipio server, I found the mongodb ``domain`` document still store ``admin.localhost`` as name. Is it a issues?

**Comment by mjpearson** [comment]
Hi, nope that's not an issue.  Domains are used by the bips collection to bind a user domain to HTTP or SMTP bip endpoints, this means that bips are namespaced to individual users.

An easy way to remember is : 

- `localhost:5000/rpc` or `localhost:5000/rest` calls are for managing resources

- `{username}.localhost:5000` calls (or, any domain calls) are namespaced to a particular account

Hope that helps, we'll be getting better documentation out in the next few weeks to cover these areas

**Comment by EricCat** [comment]
@mjpearson Thank you very much
