### ISSUE TITLE
cannot access bipio server within vagrant guest 

### ISSUE THREAD

**Issue by EricCat** [bipio-server/bipio#44]
I want to use bipio in vagrant as guest, but I found I can't access bipio from host machine(if I use others server[restify or koa and etc..], I can access successfully). Should I need setting something else for bipio?

**Comment by mjpearson** [comment]
I'm not sure on your exact setup but it could be that bipio listens on localhost only by default. This rule can be relaxed editing `config/default.json` and either stripping out the `server.host` config or setting it to another interface.

The template for it is in the distributed config : https://github.com/bipio-server/bipio/blob/master/config/config.json-dist#L19

**Comment by EricCat** [comment]
@mjpearson Thanks. I fixed it. 
Solution:  set server.host  to ``0.0.0.0``
