### ISSUE TITLE
Continue the process, after recovery the broken bipio server.

### ISSUE THREAD

**Issue by EricCat** [bipio-server/bipio#46]
For example, there is a bip with three channels, when channel 2 processing the workflow, bipio server breaking down. 
After restart bipio server, I want to process the workflow from channel 2, not start from beginning. How to deal with this situation? 
I think maybe need to handle rabbitmq queue. Is there some api for handle rabbitmq ?

**Comment by mjpearson** [comment]
Are you seeing a specific error being raised?  The number of channels is arbitrary, but if a specific error is on a pod then investigation can be focused.  Can you please post any output received by the server (if any?) or otherwise post your transforms configuration (minus any personal info)

**Comment by EricCat** [comment]
@mjackson Thank you.
Sorry, maybe I'm not explain clear.
This is not a error, just a feature I want to implement. I want to store the process sessions.

**Comment by mjpearson** [comment]
Hi, thanks for clarifying :)

durability can be tweaked by in the server config (config/default.json) - the rabbit > exchanges > bastion_generic > queue_default which are the node-amqp constructor options for setting durability on the default job queue (defaults to on).

processing should continue if either the bipio server or rabbitmq server is restarted, as the payloads in rabbit always contain their parent graph and a pointer to the next hop.  If you're finding that processing isn't continuing after a reboot then that's probably a bug and needs investigating

**Comment by EricCat** [comment]
@mjackson Thanks for your explain.
