### ISSUE TITLE
How to deploying on security domain

### ISSUE THREAD

**Issue by EricCat** [bipio-server/bipio#50]
When I deployed bipio to my security domain ``https://proxy.xxxx.com``. 
I got response status 500 errors. _I tested others api, they can works_
How should I debug bipio deploying security domain?

I've updated __domain_public__ as ``proxy.xxxx.com``

**Comment by mjpearson** [comment]
Hi, 500 errors if they're being generated by bipio will appear in the bipio server log as an exception with a stack trace. Or otherwise in the logs of your proxy

do you have a sample request and response payload, generating the 500?

**Comment by EricCat** [comment]
Hi @mjpearson , My bipio server logs looks normally, same as I using ``localhost`` . Indeed, I'm deploying to heroku. bipio looks very well on running logs, but just cannot get response.
Excpet of domain_public, where should I still need to setting?
