### ISSUE TITLE
Status 500 after installing

### ISSUE THREAD

**Issue by fnkr** [bipio-server/bipio#52]
I installed bipio from git (commit 647834a) but if I try to access if from web I get a 500 response.
```
$ curl http://localhost:9009
$ curl -I http://localhost:9009
HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Origin: undefined
Access-Control-Allow-Headers: *
Access-Control-Allow-Methods: GET,POST,PUT,DELETE
Access-Control-Allow-Credentials: true
set-cookie: sid=s%3A2jJUZO7vtRjulzaiVceR3C0q3ze4P-aZ.eIzhl%2BtJ5BDBEJLHcP8R5T59Xqcu7TGzqQSRxPvQiBY; Path=/; Expires=Tue, 19 May 2015 08:17:25 GMT; HttpOnly
Date: Tue, 19 May 2015 07:17:25 GMT
Connection: keep-alive
```

- [server.log](https://ge1.me/37c36ea6729544108fcf)
- [w_server.log.19-05-2015](https://ge1.me/ed967e2446c443d28fc1)
- [w_transaction.log.19-05-2015](https://ge1.me/ed279454c8e441fdbb1e)

**Comment by mjpearson** [comment]
A new version of the server 0.4.x was just released, is this error still happening?
