### ISSUE TITLE
Creation of bips does not work

### ISSUE THREAD

**Issue by offlinehacker** [bipio-server/bipio#54]
I get the following error when trying to create bips on my local instance using web interface:

```
{"message":"ValidationError: Invalid, Inactive or Missing Channel In Hub"}
```

I also get 404 on get_transform_hint, which might be related.

**Comment by mjpearson** [comment]
Hi, this validation rule has been dropped in the latest server 0.4.x and should no longer appear

The 404 for get_transform_hint is usually fine, it's part of transform discovery, so if the system hasn't 'learnt' about any transforms, it will 404.
