### ISSUE TITLE
It can't catch my own Facebook message on my wall 

### ISSUE THREAD

**Issue by mikefaille** [bipio-server/bipio#58]
To reproduce : 

Facebook When A Link Is Posted --> Facebook Post To Your Timeline

Destination configuration : 
New message :
 Message

URL : 
empty

**Comment by mikefaille** [comment]
Note, with same Facebook account I get it work using IFFT

**Comment by mjpearson** [comment]
Hi, this was an issue with application provisioning on Facebook and has been fixed :)  You should see a list of pages and be able to post to them now, if you're using https://bip.io hosted site and server.
