### ISSUE TITLE
Trim URL in bipio panel

### ISSUE THREAD

**Issue by evilebottnawi** [bipio-server/bipio#63]
In page https://bip.io/dash/account when i mount self-hosted bipio field URL must be trim on `/`.
I input value `https://mybipioserver.com/` and get request on server

192.168.0.1 - itgalaxy [03/Nov/2015:11:34:44 +0300] "GET //status HTTP/1.1" 404 20 "https://bip.io/dash/account" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36" "-"
192.168.0.1 - admin [03/Nov/2015:11:34:45 +0300] "GET //login HTTP/1.1" 404 19 "https://bip.io/dash/account" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36" "-"

With two `//`. Perhaps the mistake was not written there.

**Comment by mjpearson** [comment]
thankyou, a fix for this has been pushed out
