### ISSUE TITLE
Bump version on package and refactoring to support node LTS node 4.2.1

### ISSUE THREAD

**Issue by evilebottnawi** [bipio-server/bipio#64]
If we need maintenance, let me know, I am ready to help.

**Comment by mjpearson** [comment]
Hello, bip.io  0.4.51 has been tested for compatability with node v4.2.3 and looks to be working fine.

The problematic dependencies were anything using `bindings` or `iconv-lite`, which include the bipio server and these pods

* html
* flow
* zoho
* evernote
* google-drive
* minecraft 

html and flow are core bipio dependencies and will need to be reinstalled, as will any pods from the remaining list.
