### ISSUE TITLE
Can not deploy a local instance at all

### ISSUE THREAD

**Issue by stevenmcastano** [bipio-server/bipio#65]
the npm scripts fail, the docker deployment runs but can't connect, the ui shows that it failed verification.... is there a decent writeup to get this done?

**Comment by mjpearson** [comment]
Hi, thanks for the note, there was an npm dependency issue and have deployed a fix for bipio npm version 0.4.50.  I'll investigate and try to reproduce the docker issue in https://github.com/bipio-server/bipio-docker/issues/7

For the UI to mount correctly over SSL, make sure to select 'Y' for this option during interactive setup : 

`? Enable SSL? This will let you mount this server from the https://bip.io dashboard Yes`.  

As it's a self signed certificate, and depending on your browsers security policy, visit `https://localhost:5000` first to accept the certificate.  The UI will then be able to load your server through the mount tool
