### ISSUE TITLE
Is Bip.io community still alive?

### ISSUE THREAD

**Issue by JasonShin** [bipio-server/bipio#74]
It seems like Bip.io is the best alternative to Zapier at the moment considering that it's open source. Is it still alive?

**Comment by JasonShin** [comment]
Just following up on the previous reply. So what is happening with the project? Is anyone still working on it? I'd love to join and help.

**Comment by JasonShin** [comment]
It seems like no one is maintaining this anymore =(

**Comment by hyrmedia** [comment]
That is pretty unfortunate.. I was hoping this project would take off! Of course one of us could always fork and keep it going ;) I just don't have time to work on it right now.

**Comment by sburr** [comment]
Yes

**Comment by JasonShin** [comment]
Hi guys, I am building an open source reboot of Bipio. Our slack team is based in https://bipioteam.slack.com. Please request invitation to myself or @serri588 .
Core server - https://github.com/JasonShin/BipHub
Frontend - https://github.com/JasonShin/Biphub-frontend

**Comment by JasonShin** [comment]
Hi, I am building a open source clone of Bipio but with much newer tech stacks and coding standards. Development is currently going on and please come and join us.

**Comment by jcrben** [comment]
@JasonShin are you still active in that slack channel? I see that things have been moved to https://gitlab.com/bipio and https://gitlab.com/biphub
